--country
INSERT INTO `behind-the-project`.country (country) VALUES ('Argentina');

--province
INSERT INTO `behind-the-project`.province (province,country_id) VALUES ('Chaco',1);
INSERT INTO `behind-the-project`.province (province,country_id) VALUES ('Buenos Aires, Ciudad Autónoma de',1);
INSERT INTO `behind-the-project`.province (province,country_id) VALUES ('Córdoba',1);
INSERT INTO `behind-the-project`.province (province,country_id) VALUES ('Santa Fe',1);
INSERT INTO `behind-the-project`.province (province,country_id) VALUES ('Chubut',1);
INSERT INTO `behind-the-project`.province (province,country_id) VALUES ('Tucumán',1);
INSERT INTO `behind-the-project`.province (province,country_id) VALUES ('Buenos Aires',1);
INSERT INTO `behind-the-project`.province (province,country_id) VALUES ('Salta',1);
INSERT INTO `behind-the-project`.province (province,country_id) VALUES ('San Juan',1);
INSERT INTO `behind-the-project`.province (province,country_id) VALUES ('Corrientes',1);
INSERT INTO `behind-the-project`.province (province,country_id) VALUES ('Jujuy',1);
INSERT INTO `behind-the-project`.province (province,country_id) VALUES ('Misiones',1);
INSERT INTO `behind-the-project`.province (province,country_id) VALUES ('Santiago del Estero',1);
INSERT INTO `behind-the-project`.province (province,country_id) VALUES ('Entre Ríos',1);
INSERT INTO `behind-the-project`.province (province,country_id) VALUES ('Neuquén',1);
INSERT INTO `behind-the-project`.province (province,country_id) VALUES ('Formosa',1);
INSERT INTO `behind-the-project`.province (province,country_id) VALUES ('Mendoza',1);
INSERT INTO `behind-the-project`.province (province,country_id) VALUES ('La Rioja',1);
INSERT INTO `behind-the-project`.province (province,country_id) VALUES ('San Luis',1);
INSERT INTO `behind-the-project`.province (province,country_id) VALUES ('Catamarca',1);
INSERT INTO `behind-the-project`.province (province,country_id) VALUES ('Río Negro',1);
INSERT INTO `behind-the-project`.province (province,country_id) VALUES ('La Pampa',1);
INSERT INTO `behind-the-project`.province (province,country_id) VALUES ('Santa Cruz',1);
INSERT INTO `behind-the-project`.province (province,country_id) VALUES ('Tierra del Fuego, Antártida e Islas del Atlántico Sur',1);

--city
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Resistencia',1);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Buenos Aires',2);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Córdoba',3);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Rosario',4);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Comodoro Rivadavia',5);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('San Miguel de Tucumán',6);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Mar del Plata',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Salta',8);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('San Juan',9);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Lanús',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Florencio Varela',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Santa Fe',4);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Corrientes',10);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('San Salvador de Jujuy',11);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Bahía Blanca',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Posadas',12);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Santiago del Estero',13);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Paraná',14);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Merlo',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('González Catán',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Neuquén',15);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Quilmes',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Banfield',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Formosa',16);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('José C. Paz',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('La Plata',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Godoy Cruz',17);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Isidro Casanova',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('La Rioja',18);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Berazategui',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('San Luis',19);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('José María Ezeiza',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('San Nicolás de los Arroyos',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Catamarca',20);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Río Cuarto',3);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('San Miguel',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Concordia',14);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Rafael Castillo',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('San Justo',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Ituzaingó',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Temperley',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Ramos Mejía',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('San Martín',17);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Tandil',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Puerto Madryn',5);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Mendoza',17);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('San Carlos de Bariloche',21);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Lomas de Zamora',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Villa Mercedes',19);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Bernal',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Esteban Echeverría',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Gualeguaychú',14);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('San Rafael',17);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Castelar',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('La Banda',13);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Santa Rosa',22);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Berisso',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Libertad',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Morón',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Burzaco',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Zárate',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Río Gallegos',23);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Caseros',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Villa Luzuriaga',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Trelew',5);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Ciudad General Belgrano',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Rafaela',4);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('San Francisco Solano',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Pergamino',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Campana',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Olavarría',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Monte Chingolo',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Junín',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Presidencia Roque Sáenz Peña',1);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Luján',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('General Roca',21);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Remedios de Escalada',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Pilar',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Gobernador Gálvez',4);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Necochea',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Ezpeleta',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Villa María',3);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Venado Tuerto',4);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('San Ramón de la Nueva Orán',8);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Concepción del Uruguay',14);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Goya',10);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Bella Vista',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Lomas del Mirador',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Reconquista',4);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Las Heras',17);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Oberá',12);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Wilde',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Santo Tomé',4);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Villa Carlos Paz',3);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Villa Domínico',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('San Francisco',3);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Los Polvorines',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Tartagal',8);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Sarandí',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Chajarí',14);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Viedma',21);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('San Pedro',11);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Punta Alta',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Rafael Calzada',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('General Pico',22);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Ushuaia',24);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Azul',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Chivilcoy',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Mercedes',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Cruz del Eje',3);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Caleta Olivia',23);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('El Talar de Pacheco',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Villaguay',14);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Libertador General San Martín',11);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Alta Gracia',3);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('La Reja',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('San Lorenzo',10);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Longchamps',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Villa Constitución',4);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Tres Arroyos',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Río Tercero',3);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Pinamar',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('San Isidro',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Esperanza',4);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Gualeguay',14);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Villa Alsina',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('José Mármol',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Balcarce',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Aristóbulo del Valle',12);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Haedo',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Granadero Baigorria',4);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Esquel',2);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Nueve de Julio',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Dock Sur',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Munro',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Cutral-Có',15);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Villa Adelina',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Casilda',4);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Chacabuco',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Centenario',15);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Bell Ville',3);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Chilecito',18);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Bragado',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Plottier',15);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('La Calera',3);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Zapala',15);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Rawson',5);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Jesús María',3);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Río Grande',24);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Victoria',14);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Villa Ángela',1);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Villa Regina',21);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Villa Celina',2);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Villa Gesell',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Capitán Bermúdez',4);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Cañada de Gómez',4);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Baradero',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Villa Allende',3);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Adrogue',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('San Martín de los Andes',15);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Marcos Juárez',3);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Dolores',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Firmat',4);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Colón',14);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Lincoln',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Avellaneda',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Coronel Suárez',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Tapiales',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Veinticinco de Mayo',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Tunuyán',17);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Deán Funes',3);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('El Calafate',23);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Chascomús',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Laboulaye',3);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Brandsen',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('General Martín Miguel de Güemes',8);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Vera',4);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Charata',1);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Lobos',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Coronda',4);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('General Juan Madariaga',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Eldorado',12);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Ayacucho',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Santa María',20);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Federación',14);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('San Antonio Oeste',21);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Villa del Rosario',3);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Villa Paranacito',14);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Carmen de Areco',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('San Cristóbal',4);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Puerto Deseado',23);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Añatuya',13);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('La Quiaca',11);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('San Javier',4);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Frías',13);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Joaquín V. González',8);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Chos Malal',15);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Rosario del Tala',14);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('San Salvador',14);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Junín de los Andes',15);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('La Carlota',3);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Malargüe',17);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Cafayate',8);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Oliva',3);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Coronel Dorrego',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Cerrillos',8);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Monte Quemado',13);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Humahuaca',11);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Belén',20);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Villa La Angostura',15);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Sarmiento',5);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Benito Juárez',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('San José de Feliciano',14);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Choele Choel',21);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Castelli',1);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Chamical',18);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Helvecia',4);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('San Julián',23);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Santa Rosa de Río Primero',3);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Carhué',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Rinconada',11);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Ingeniero Guillermo N. Juárez',16);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Villa Cura Brochero',3);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Chepes',18);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Villa Huidobro',3);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('General Conesa',21);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('San Antonio de los Cobres',8);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Macachín',22);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Loncopué',15);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Perito Moreno',23);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Aluminé',15);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Gobernador Gregores',23);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Abra Pampa',11);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Victorica',22);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Puerto Santa Cruz',23);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('La Paz',17);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Comandante Fontana',16);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Concepción',10);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Valcheta',21);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Piedra del Águila',15);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Tafí del Valle',6);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('San Agustín',3);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Picún Leufú',15);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Pampa del Infierno',1);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Chumbicha',20);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Maquinchao',21);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Añelo',15);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Buta Ranquil',15);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('San Francisco del Chañar',3);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Melincué',4);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('José de San Martín',5);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Trancas',6);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Alto Río Senguer',5);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Sierra Colorada',21);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Villa Tulumba',3);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('El Huecú',15);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('San Carlos',3);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Salsacate',3);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Paso de Indios',5);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Tecka',5);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Las Lajas',15);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Susques',11);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Las Coloradas',15);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Pilcaniyeu',21);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Rodeo',9);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Gastre',5);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Tinogasta',20);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Telsen',5);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Las Plumas',5);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Olivos',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('General San Martín',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Hurlingham',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Banda del Río Salí',6);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Villa Nueva',17);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Chimbas',9);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Tigre',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Santa Lucía',9);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Belén de Escobar',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Guernica',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Rivadavia',9);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Bernardo de Irigoyen',12);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Yerba Buena',6);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Ensenada',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Villa Krause',9);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Mar del Tuyú',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('General Rodríguez',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Maipú',17);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('San Fernando',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Marcos Paz',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('San Isidro de Lules',6);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Tafí Viejo',6);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Palpalá',11);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('El Carmen',11);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Villa Aberastain',9);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('San Vicente',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Aguilares',6);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Famaillá',6);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Cosquín',3);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('San José',20);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Monteros',6);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Capilla del Señor',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Monte Hermoso',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Cañuelas',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Puerto Rico',12);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Villa Alberdi',6);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Leandro N. Alem',12);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Apóstoles',12);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Alba Posse',12);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Campo Grande',12);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('San Ignacio',12);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Ramallo',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Fernández',13);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Puerto Esperanza',12);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Santa Ana',12);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Termas de Río Hondo',13);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Capitán Sarmiento',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('San Antonio de Areco',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('San Cosme',10);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Luján de Cuyo',17);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Miramar',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Simoca',6);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Arrecifes',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('El Soberbio',12);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Montecarlo',12);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Quitilipi',1);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Chicoana',8);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Salto',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('San Andrés de Giles',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('General Las Heras',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('La Cocha',6);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Villa San Isidro',9);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('San Antonio',11);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Las Rosas',4);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Diamante',14);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Clorinda',16);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Santa Rosa del Conlara',19);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Monte Caseros',10);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Tupungato',17);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('San Bernardo',1);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Sastre',4);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Las Breñas',1);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Concepción de la Sierra',12);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('San Miguel del Monte',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Machagai',1);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Saladillo',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Puerto Tirol',1);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Itatí',10);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Campo Largo',1);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Saladas',10);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Rojas',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Suipacha',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Magdalena',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Navarro',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Vedia',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Burruyacú',6);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Salliqueló',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Colonia Elisa',1);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Paso de los Libres',10);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('General Arenales',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('La Leonesa',1);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('General Belgrano',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Corzuela',1);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Alberti',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Ranchos',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Mburucuyá',10);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Pehuajó',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Gobernador Ingeniero Valentín Virasoro',10);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Carlos Casares',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Makallé',1);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Nogoyá',14);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Roque Pérez',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Trenque Lauquen',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Tres Isletas',1);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('General Viamonte',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('La Caldera',8);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Margarita Belén',1);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('General Pinedo',1);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('General José de San Martín',1);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Rosario de Lerma',8);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Villa Media Agua',9);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Empedrado',10);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Bañado de Ovanta',20);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Graneros',6);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Concarán',19);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Esquina',10);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Metán',8);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('San Roque',10);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Coronel Vidal',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Tres Lomas',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Realicó',22);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Pirané',16);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('San Luis del Palmar',10);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Las Flores',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('San Carlos de Bolívar',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Villa Berthet',1);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Arraga',13);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Tilcara',11);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Aimogasta',18);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Villa del Totoral',3);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Verónica',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Henderson',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Pigüé',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Santa Sylvina',1);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Nuestra Señora del Rosario de Caa Catí',10);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Rosario de la Frontera',8);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Herrera',13);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Brea Pozo',13);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Presidencia de la Plaza',1);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Caucete',9);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Curuzú Cuatiá',10);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Ameghino',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Espinillo',16);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Intendente Alvear',22);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Federal',14);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('San Francisco de Laishí',16);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Villa Atamisqui',13);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Daireaux',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('General Pinto',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Hermoso Campo',1);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('General Villegas',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Villa Santa Rosa',9);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Coronel Pringles',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Alvear',10);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('La Candelaria',8);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('General Enrique Mosconi',16);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('La Merced',20);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Santa Clara',11);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Andalgalá',20);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('General Lavalle',17);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Lobería',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Los Telares',13);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('La Viña',8);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Quemú Quemú',22);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Sauce',10);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Rauch',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('La Toma',19);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Berón de Astrada',10);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Pellegrini',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('General Alvear',17);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Tornquist',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Médanos',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('González Chaves',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Aminga',18);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Villa del Salvador',9);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Carlos Tejedor',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Bandera',13);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Catriló',22);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Laprida',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('La Consulta',17);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Nueva Esperanza',13);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Toay',22);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('San Cayetano',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Garza',13);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Esquiú',20);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Trenel',22);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('La Cañada',13);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Eduardo Castex',22);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Guaminí',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Winifreda',22);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('San Blas de los Sauces',18);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Santa Victoria',8);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Sumampa',13);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Pozo Hondo',13);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Puan',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Olta',18);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Guatraché',22);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Cachí',8);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Villa Ojo de Agua',13);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Carmen de Patagones',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Valle Grande',11);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Tapalqué',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('San Francisco del Monte de Oro',19);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('General La Madrid',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Villa de María',3);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('La Puerta',20);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('La Cruz',10);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Quimilí',13);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Suncho Corral',13);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Selva',13);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Saujil',20);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Parera',22);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Milagro',18);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Sañogasta',18);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Tostado',4);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('El Alto',20);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Molinos',8);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Iruya',8);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('San José de Jáchal',9);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Leleque',5);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Campo Gallo',13);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Famatina',18);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('San Agustín de Valle Fértil',9);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Tumbaya',11);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Ancasti',20);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Bernasconi',22);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('General Guido',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Andacollo',15);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('General Acha',22);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Guachipas',8);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Malanzán',18);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Laguna Yema',16);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Pila',7);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Villa Unión',18);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Ulapes',18);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Gaimán',5);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Santa Catalina',11);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Río Colorado',21);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Tama',18);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Patquía',18);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Charadai',1);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Villa General Roca',19);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Buena Esperanza',19);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Santa Isabel',22);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('La Poma',8);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Tamberías',9);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Villa Castelli',18);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('El Cuy',21);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Vinchina',18);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Algarrobo del Águila',22);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Ñorquinco',21);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Camarones',5);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Puelches',22);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Limay Mahuida',22);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Antofagasta de la Sierra',20);
INSERT INTO `behind-the-project`.city (city,province_id)  VALUES ('Cuchillo Có',22);